In [ ]:
# in order for this to work f2py needs to be installed (usually present in an anaconda distribution)
# also in order to have fortran in the notebook pip install -U fortran-magic is needed

In [6]:
import numpy as np

In [2]:
#load fortran magic
%load_ext fortranmagic

/home/mamonu/anaconda3/lib/python3.6/site-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


In [3]:

%%fortran --link lapack

subroutine solve(A, b, x, n)
    ! solve the matrix equation A*x=b using LAPACK
    implicit none

    real*8, dimension(n,n), intent(in) :: A
    real*8, dimension(n), intent(in) :: b
    real*8, dimension(n), intent(out) :: x

    integer :: pivot(n), ok

    integer, intent(in) :: n
    x = b

    ! find the solution using the LAPACK routine SGESV
    call DGESV(n, 1, A, n, pivot, x, n, ok)

end subroutine

In [10]:
size=5

A=  np.random.random((size,size))
B=  np.random.random((size,size))
b = np.array(np.random.uniform(1, 10, size))

In [8]:
%timeit np.linalg.solve(A, b)
%timeit solve(A,b)

234 µs ± 60.1 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
387 µs ± 850 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
%timeit np.dot(np.linalg.inv(A), b) 

291 µs ± 3.41 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [15]:
x1=np.linalg.solve(A, b)

In [16]:
x2=solve(A,b)

In [17]:
x3=np.dot(np.linalg.inv(A), b) 

In [18]:
x1,x2,x3

(array([-137.74228879,  149.51465788,  103.65861098,  -11.0260971 ,
         -43.0154306 ]),
 array([-137.74228879,  149.51465788,  103.65861098,  -11.0260971 ,
         -43.0154306 ]),
 array([-137.74228879,  149.51465788,  103.65861098,  -11.0260971 ,
         -43.0154306 ]))